✨ Added PollResponse API
RocketMeet/RocketMeet-mailer pull request #22
Opened 2021-03-12 10:14 UTC by PushkarDureja

### Changes implemented in order to solve [#95](https://github.com/RocketMeet/RocketMeet-client/issues/95) 

- Created an API `/pollResponse` which is responsible for sending mails
- Created an email template

2021-03-12 10:23 UTC, AnandBaburajan commented
Congrats and thanks! The failing tests are not your fault, by the way. We're looking into it.

2021-03-12 14:18 UTC, AthulJoshi commented
@PushkarDureja Thanks for the PR.
But I have one concern, i.e we are sending the mail to the poll creator right? So is there a use for the receiverIDs.

2021-03-12 14:28 UTC, PushkarDureja commented
You are right, receiverIds array will always be of length 1 in this case. I reused the MailerArg interface here because i thought creating a new interface or altering the interface for a single field is not effective in this case

2021-03-12 14:36 UTC, AthulJoshi commented
Is that good practice? @AnandBaburajan. Also, the senderID itself is the receiverID in this case, so do we need that redundancy? I guess it is okay to change the interface.

2021-03-12 14:48 UTC, PushkarDureja commented
Umm, I dont think sender email will be same as receiver. Receiver will always be the poll creator where as sender email will always be of logged in user and is used as a parameter in nodemailer @AthulJoshi

2021-03-12 14:58 UTC, AthulJoshi commented on src/routes/v1/pollResponse.ts
> +  }
We would be making a POST request from the client side, so usually senderName and senderEmailID is passed to be set at the ```from``` field of nodemailer. But in this case, the sender is RocketMeet, so we wont be needing those 2 fields.

2021-03-12 14:58 UTC, AthulJoshi commented on src/routes/v1/pollResponse.ts
> +        from: `RocketMeet <${email}>`,
See this line, and those 2 fields aren't used anywhere, so those 2 wont be needed I guess.

2021-03-12 15:13 UTC, PushkarDureja commented on src/routes/v1/pollResponse.ts
> +        from: `RocketMeet <${email}>`,
If you see line  24, sender's name is used there and about sender email, I thought using it in the `reply to` parameter was the right thing but I was not sure. What do you think?

2021-03-12 15:29 UTC, AnandBaburajan commented
I'll take a final look at the code once the doubts here are cleared, but a comment:

> the senderID itself is the receiverID in this case

Since this PR fixes https://github.com/RocketMeet/RocketMeet-client/issues/95 the `senderEmailID` would be voter's email ID and `receiverID` would be the poll creator's email ID. Please let me know if I got something wrong!

2021-03-16 05:54 UTC, AthulJoshi commented on src/routes/v1/pollResponse.ts
> +        from: `RocketMeet <${email}>`,
Yea, that would be alright

2021-03-16 05:54 UTC, AthulJoshi commented
> I'll take a final look at the code once the doubts here are cleared, but a comment:
> 
> > the senderID itself is the receiverID in this case
> 
> Since this PR fixes [RocketMeet/RocketMeet-client#95](https://github.com/RocketMeet/RocketMeet-client/issues/95) the `senderEmailID` would be voter's email ID and `receiverID` would be the poll creator's email ID. Please let me know if I got something wrong!
> 
> Edit:
> 
> > Receiver will always be the poll creator where as sender email will always be of logged in user
> 
> Yep (^_^")

I guess it's ok then, maybe change the receiverIDs array to just receiverID?

2021-03-16 08:53 UTC, PushkarDureja commented
@AthulJoshi But for that, We need to create a new Interface which will be used just for this purpose which I dont think is a good approach. Can you suggest any other alternative ?

2021-03-16 08:58 UTC, AthulJoshi commented
> @AthulJoshi But for that, We need to create a new Interface which will be used just for this purpose which I dont think is a good approach. Can you suggest any other alternative ?

I don't get it. You have already created an interface here, it's not imported right? So why can't a field be changed? Oh is it because it would cause confusions in the frontend api calls?

2021-03-16 09:14 UTC, PushkarDureja commented
Yes, I have used a predefined Interface in frontend, So in order to change a field, I think I have to create a new Interface in frontend 

> > @AthulJoshi But for that, We need to create a new Interface which will be used just for this purpose which I dont think is a good approach. Can you suggest any other alternative ?
> 
> I don't get it. You have already created an interface here, it's not imported right? So why can't a field be changed? Oh is it because it would cause confusions in the frontend api calls?

2021-03-16 09:33 UTC, AthulJoshi commented
I guess everything is good then. @AnandBaburajan please have a look .

2021-03-16 15:53 UTC, PushkarDureja commented
@AnandBaburajan can you please review it?

2021-03-16 18:34 UTC, AnandBaburajan requested changes
I've added one comment, PTAL. Also if you can, try to align your code with the rest of the code. Using Prettier would help I think.

2021-03-16 18:34 UTC, AnandBaburajan commented on src/routes/v1/pollResponse.ts
> +    const filePath = path.join(__dirname, '../../../template/pollResponse.html');
I'm curious on why the auth `data.senderEmailID !== req.currentUser.email` check was removed from here.

2021-03-16 18:49 UTC, PushkarDureja commented on src/routes/v1/pollResponse.ts
> +    const filePath = path.join(__dirname, '../../../template/pollResponse.html');
My bad, I will add it back in the next commit along with code alignment.

2021-03-16 19:02 UTC, PushkarDureja commented on src/routes/v1/pollResponse.ts
> +    const filePath = path.join(__dirname, '../../../template/pollResponse.html');
> I've added one comment, PTAL. Also if you can, try to align your code with the rest of the code. Using Prettier would help I think.

I checked my code but didn't find any misalignment, nor did I get any warnings from ES-Lint or prettier. Can you please specify the part where you think the code is unaligned. Sorry if I missed something :(

2021-03-16 19:07 UTC, AnandBaburajan commented on src/routes/v1/pollResponse.ts
> +    const filePath = path.join(__dirname, '../../../template/pollResponse.html');
Check lines 19 - 21. But I think that would be fixed with the auth check. You won't get any warnings for misalignments, but Prettier automatically aligns the code for you (not sure if it needs to be configured to do that).

2021-03-17 14:37 UTC, AnandBaburajan approved these changes
Looks good, thanks, merging :D

2021-03-17 14:38 UTC, merged

2021-03-17 14:38 UTC, AnandBaburajan commented
@AthulJoshi please update the API docs too whenever you're free.

2021-03-17 15:10 UTC, PushkarDureja commented
> Looks good, thanks, merging :D

Thanks, Great working with you, will surely work on other issues too :)